name: kgg
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - rdkit
  - pip
  - pip:
      - torch==2.7.1+cu118 --index-url https://download.pytorch.org/whl/cu118
      - torchvision --index-url https://download.pytorch.org/whl/cu118
      - torchaudio --index-url https://download.pytorch.org/whl/cu118
      - pyg_lib -f https://data.pyg.org/whl/torch-2.7.0+cu118.html
      - torch_scatter -f https://data.pyg.org/whl/torch-2.7.0+cu118.html
      - torch_sparse -f https://data.pyg.org/whl/torch-2.7.0+cu118.html
      - torch_cluster -f https://data.pyg.org/whl/torch-2.7.0+cu118.html
      - torch_spline_conv -f https://data.pyg.org/whl/torch-2.7.0+cu118.html
      - torch_geometric
      - joblib
      - scikit-learn
      - pytest
      - black
